# Generated by Django 5.0.7 on 2024-07-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='apellido_paterno',
        ),
    ]
